/**
 * AUTO-GENERATED by scripts/generate-api-catalog.ts
 * Do not edit manually.
 */

import bulk_operations_json from "./bulk-operations.json";
import businesses_json from "./businesses.json";
import catalog_products_json from "./catalog-products.json";
import channels_json from "./channels.json";
import fulfillments_json from "./fulfillments.json";
import location_addresses_json from "./location-addresses.json";
import metafields_json from "./metafields.json";
import onboarding_json from "./onboarding.json";
import orders_json from "./orders.json";
import stores_json from "./stores.json";
import transactions_json from "./transactions.json";

export const DOMAIN_REGISTRY: Record<string, unknown> = {
  "bulk-operations": bulk_operations_json,
  businesses: businesses_json,
  "catalog-products": catalog_products_json,
  channels: channels_json,
  fulfillments: fulfillments_json,
  "location-addresses": location_addresses_json,
  metafields: metafields_json,
  onboarding: onboarding_json,
  orders: orders_json,
  stores: stores_json,
  transactions: transactions_json,
};
